from python:3.8-slim-buster

run apt update -y && apt install awscli -y
WORKDIR /app

COPY ./app

RUN pip install -r requirements.txt
RUN pip install --upgrade accelerate
RUN pip uninstall -y transformers accelerate
RUN pip install transformers acceleration

CMD ["python3", "app.py"]